### ISSUE TITLE
On reproducing the hallucinations generation

### ISSUE THREAD

**Issue by avidale** [deep-spin/hallucinations-in-nmt#1]
Hello and thanks for your inspiring work!
Could you please release the script that you have used to generate translations?
I am currently working on an alternative method of hallucination mitigation, and I want to evaluate it on your data. But to do this, I have to reproduce the generation of hallucinated translations in the first place. 
Best wishes, 
David Dale

**Comment by nunonmg** [comment]
Hi David,
Sorry for the delay. Do you mean the fairseq-generate code? 
Best,
Nuno

**Comment by avidale** [comment]
Hi Nuno!
Yes, I mean the fairseq-generate code. 
So far, I was able to reproduce 99.5% of the translations in the dataset published by you, which seems sufficient for my purposes. Nevertheless, it seems a good idea to publish the code that could reproduce 100% of the translations - at least, out of curiosity :-)

My 99.5%-matching translations were obtained by loaded the model with the following code:
```
from fairseq.models.transformer import TransformerModel
de2en = TransformerModel.from_pretrained(
    model_dir,
    checkpoint_file='checkpoint_best.pt',
    data_name_or_path=data_dir,
    bpe='sentencepiece', 
    sentencepiece_model=model_dir + '/sentencepiece.joint.bpe.model'
)
```
and then running `de2en.translate(text, beam=5)` on each text to produce the translations.

**Comment by nunonmg** [comment]
Hi David, 
Sorry for the delay!

We used `fairseq-generate` to obtain the translations with the following code:

```shell
fairseq-generate $DATA \
    --path ${CKPT}.pt --source-lang $src_lang --target-lang $tgt_lang --gen-subset $split --batch-size $bs --beam 5  --remove-bpe=sentencepiece --skip-invalid-size-inputs-valid-test 
```

I also found that, for some reason, it is not possible to 100% reproduce the translations that we obtained back in the beginning of 2022. I obtained the same reproducibility rate that you did. Maybe this is due to some incremental change between different fairseq versions (unfortunately, I do not have the version of fairseq that we used for this paper).

Nevertheless, it is possible to fully reproduce the model internal states from our paper by force-decoding the MTs that are provided in the dataset. This can be done by adding the flag `score-reference` to the `fairseq-generate` command. I will add this information to the main repository.

Thank you so much for noticing this!
